### PR TITLE
Added the ability to restrict page access based on role

### PR DESCRIPTION
**Pull request by brandonleute**
### Description
- Routes are now restricted by role.
- The Navbar shows the proper menu options for student and teachers.
- Teacher and student routing after login was fixed.
- Altered the keycloak setup to say encounter at the top of the pages.
image

### Tests Steps
- Create a teacher user.
You should the correct navigation options in the nav menu.
You should be routed to the classroom page.

- Create a student user and try to access the old problem search page. You should be able to access this page as a student.
You should the correct navigation options in the nav menu.
You should be routed to the problem set page.

### CODE REVIEW

**Comment by am6uno** [comment]
I brought my dockers down, removed volumes, restarted ng serve, and built again, but nothing seemed to change?


As a teacher, I don't see the problem selection page, but I still see the problem search page:
image


As a student, I still see all of the teacher-only pages: (also, I get an error related to roles when making a student)
image

**Comment by brandonleute** [comment]
Sorry I should have been a bit more clear, this branch is just made it possible to restrict page access based on role. I didn't separate all the pages into student and teacher so that it is easier to develop, we can do this at the end. I also didn't make any change to the navigation menu to hide pages that you can't access, this will be easy to do and can be done at the end. By problem selection I meant the problem search page which is is the problem selection component.

The error in the console should be fixed now.

**Comment by am6uno** [comment]
Looks good!

**Comment by am6uno** [comment]
The student can still access the `Find Problems` page (which displays all problems from all classes) when they click on the `Back to Problems` button after solving a problem.

It works just as expected though, great job!

**Comment by cgregory902** [comment]
Looks good to me!

**Comment by brandonleute** [comment]
> The student can still access the `Find Problems` page (which displays all problems from all classes) when they click on the `Back to Problems` button after solving a problem.
> 
> It works just as expected though, great job!

this should be fixed now. it should take them back to the student-problem set page.

**Pull request merged**
